export const composers = [
    {
        "name": "Ludwig van Beethoven",
        "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Joseph_Karl_Stieler%27s_Beethoven_mit_dem_Manuskript_der_Missa_solemnis.jpg/1200px-Joseph_Karl_Stieler%27s_Beethoven_mit_dem_Manuskript_der_Missa_solemnis.jpg",
        "years": "1770–1827",
        "composition": "Symphony No. 9 in D Minor, Op. 125",
        "linkComposition": "https://open.spotify.com/track/2gK0pgL5CwCxOvP0Ks9gGz?si=79a6c8e2359346b00",
        "nationality": "German",
        "style": "Romantic",
    },
    {
        "name": "Wolfgang Amadeus Mozart",
        "img": "https://fraryguitar.com/history_images/Barbara_Krafft_Wolfgang-amadeus-mozart1819.jpg",
        "years": "1756-1791",
        "composition": "Requiem in D Minor, K. 626",
        "linkComposition": "https://open.spotify.com/track/5p3xMIHQ6YoAIaSgZeOkNa?si=3a97000d6e684853",
        "nationality": "Austrian",
        "style": "Classical",
    },
    {
        "name": "Johann Sebastian Bach",
        "img": "https://cdn.topofart.com/images/artists/Haussmann/paintings-wm/haussmann-001.jpg",
        "years": "1685-1750",
        "composition": "Toccata and Fugue in D Minor, BWV 565",
        "linkComposition": "https://open.spotify.com/track/4HE2Ex0bjbj3YNXmV01OoM?si=b972c83cb80f4a42",
        "nationality": "German",
        "style": "Baroque",
    },
    {
        "name": "Frédéric Chopin",
        "img": "https://www.art-prints-on-demand.com/kunst/maximilian_fajans/Frederic-Chopin-after-Ary-Scheffer.jpg",
        "years": "1810-1849",
        "composition": "Nocturnes",
        "linkComposition": "https://open.spotify.com/track/2ZSga0mI1m1wNpxj5ZXVs6?si=aa4d9675e10c4046",
        "nationality": "Pole",
        "style": "Romantic",
    },
    {
        "name": "Johannes Brahms",
        "img": "https://lastfm.freetls.fastly.net/i/u/ar0/22cb281261714829d8e6bb6bd2016a6f.jpg",
        "years": "1833-1897",
        "composition": "Hungarian Dances, WoO 1",
        "linkComposition": "https://open.spotify.com/track/2SvULYdmPes23yZQYeLkXV?si=e08b01bc0a204cf4",
        "nationality": "German",
        "style": "Romantic",
    },
    {
        "name": "Antonio Vivaldi",
        "img": "https://www.worldhistory.org/img/c/p/1200x900/17458.png",
        "years": "1678-1741",
        "composition": "The Four Seasons (Le Quattro Stagioni)",
        "linkComposition": "https://open.spotify.com/track/6xyMABeRfPqMDmN3odcj51?si=09c056887d6b4546",
        "nationality": "Italian",
        "style": "Baroque",
    },
    {
        "name": "Franz Schubert",
        "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Franz_Schubert_by_Wilhelm_August_Rieder_1875.jpg/1200px-Franz_Schubert_by_Wilhelm_August_Rieder_1875.jpg",
        "years": "1797-1828",
        "composition": "String Quartet No. 14 in D Minor (Death and the Maiden), D. 810",
        "linkComposition": "https://open.spotify.com/track/2gyJ1eUR5F5lynz7GssrWb?si=818ac6264c7d4454",
        "nationality": "Austrian",
        "style": "Romantic",
    },
    {
        "name": "Richard Strauss",
        "img": "https://data.operabase.com/workComposers/074e8924-e9b7-48b3-81e8-23d7933cd4bc/richard-strauss-large.png",
        "years": "1864-1949",
        "composition": "Also sprach Zarathustra (Thus Spoke Zarathustra), Op. 30",
        "linkComposition": "https://open.spotify.com/track/43YwOmGUOS3zzGvj1Feszb?si=0afc855458494ab3 ",
        "nationality": "German",
        "style": "Modern",
    },
]